### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by jonnykry** [sindresorhus/fullname-cli#1]
Hi!  This sounded neat, so I wanted to give it a try.

Not sure if this is a WIP, but I came across this after installing via npm:

$ fullname --help
/usr/local/lib/node_modules/fullname-cli/cli.js:4
const meow = require('meow');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

Seems like const is conflicting with `use strict`.

**Comment by sindresorhus** [comment]
Upgrade node.

**Comment by jonnykry** [comment]
Nifty.  Thanks!
